name = "PowerModelsDataset"
uuid = "5be28bd4-3740-424f-b50b-46d9889afe5d"
authors = ["alizadehcharly@gmail.com"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
